import {login as identityLogin,signup,logout as identityLogout,getSettings,handleAuthCallback,requestPasswordRecovery,updateUser,oauthLogin,onAuthChange} from '@netlify/identity';
let account=null,settings=null,workspaces=[],active=null,pending=null,saving=null,saveTimer=null,saveFailure='',booting=true,loggingOut=false;
const originalRender=render;
const gate=document.createElement('section');gate.id='accountGate';document.body.append(gate);
const cloudKeys=['brand','archetype','clarity','dna','multiplier','funnel','guidelines','assets','brandie','kraftie','websiteBrief','visualAxes'];
const snapshot=()=>JSON.parse(JSON.stringify(Object.fromEntries(cloudKeys.filter(k=>Object.hasOwn(state,k)).map(k=>[k,state[k]]))));
function lock(){document.documentElement.classList.add('account-locked');state.session=false}
function unlock(){document.documentElement.classList.remove('account-locked');gate.hidden=true}
function panel(title,copy,content=''){gate.hidden=false;gate.innerHTML=`<div class="account-card"><img class="account-logo" src="assets/krafted-brand-os-logo.png" alt="Krafted Brand OS"><div class="kicker">Your brand. One connected workspace.</div><h1>${esc(title)}</h1><p>${esc(copy)}</p>${content}<p id="accountMessage" role="status" aria-live="polite"></p></div>`}
function message(text){const el=document.getElementById('accountMessage');if(el)el.textContent=text}
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});let result;try{result=await response.json()}catch{throw Error('Account services are unavailable. Please try again.')}if(!response.ok){const e=Error(result.error||'Request failed.');e.status=response.status;throw e}return result}
function authView(mode='login'){
 lock();const signupMode=mode==='signup',recovery=mode==='recovery',reset=mode==='reset';
 panel(reset?'Choose a new password':recovery?'Reset your password':signupMode?'Create your account':'Welcome back',reset?'Set a secure password, then return to your Brand OS.':recovery?'We’ll send a password reset link if an account exists.':signupMode?'Register with your email and verify it to access Brand OS. No payment required.':'Sign in to your private Brand OS.',`<form id="secureAuthForm">${signupMode?'<label for="secureName">Full name</label><input id="secureName" autocomplete="name" required maxlength="100">':''}${!reset?'<label for="secureEmail">Email</label><input id="secureEmail" type="email" autocomplete="email" required>':''}${!recovery?`<label for="securePassword">Password</label><input id="securePassword" type="password" autocomplete="${signupMode||reset?'new-password':'current-password'}" minlength="${signupMode||reset?12:1}" required>${signupMode||reset?'<small>Use at least 12 characters.</small>':''}`:''}<button class="btn orange full" type="submit">${reset?'Save new password':recovery?'Send reset link':signupMode?'Create account':'Sign in'}</button></form><div class="account-links">${!signupMode&&!recovery&&!reset&&!settings?.disableSignup?'<button type="button" id="showSignup">Create an account</button>':''}${!recovery&&!reset?'<button type="button" id="showRecovery">Forgot password?</button>':''}${mode!=='login'?'<button type="button" id="showLogin">Back to sign in</button>':''}</div><div id="oauthButtons" class="account-links"></div>`);
 document.getElementById('showSignup')?.addEventListener('click',()=>authView('signup'));document.getElementById('showRecovery')?.addEventListener('click',()=>authView('recovery'));document.getElementById('showLogin')?.addEventListener('click',()=>authView());
 if(mode==='login')for(const [provider,enabled] of Object.entries(settings?.providers||{})){if(enabled&&provider!=='email'){const b=document.createElement('button');b.type='button';b.textContent='Continue with '+provider;b.onclick=()=>oauthLogin(provider);document.getElementById('oauthButtons').append(b)}}
 document.getElementById('secureAuthForm').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button[type="submit"]');button.disabled=true;message('Please wait…');try{const email=document.getElementById('secureEmail')?.value.trim(),password=document.getElementById('securePassword')?.value;if(reset){await updateUser({password});await refreshAccount()}else if(recovery){await requestPasswordRecovery(email);message('If that address has an account, a reset link has been sent.')}else if(signupMode){await signup(email,password,{full_name:document.getElementById('secureName').value.trim()});authView();message('Check your email to verify your account, then sign in.')}else{await identityLogin(email,password);await refreshAccount()}}catch(error){message(error.message||'Could not complete sign in. Please retry.')}finally{button.disabled=false}};
}
function verificationView(){lock();panel('Verify your email','Verify your email address to open your Brand OS.',`<button class="btn orange full" id="checkAccess">Check access again</button><button class="btn secondary full" id="gateLogout">Sign out</button>`);document.getElementById('checkAccess').onclick=refreshAccount;document.getElementById('gateLogout').onclick=logout}
function accountControls(){let el=document.getElementById('accountControls');if(!el){el=document.createElement('div');el.id='accountControls';document.querySelector('.top .userbox').prepend(el)}el.innerHTML='<button type="button" class="workspace-header-button" onclick="openAccountPanel()">Account</button><span id="cloudStatus" role="status"></span>';cloudStatus()}
function cloudStatus(){const el=document.getElementById('cloudStatus');if(el)el.textContent=saveFailure?'Save failed':saving||pending?'Saving…':'Saved to cloud';let warning=document.getElementById('cloudSaveWarning');if(!warning){warning=document.createElement('div');warning.id='cloudSaveWarning';warning.className='ai-status';document.body.append(warning)}warning.hidden=!saveFailure;warning.replaceChildren();if(saveFailure){const text=document.createElement('span');text.textContent=saveFailure+' Your unsynced draft is kept in this browser.';warning.append(text);const b=document.createElement('button');b.className='btn secondary';b.textContent='Retry save';b.onclick=()=>flushCloud().catch(()=>{});warning.append(b)}}
const draftKey=()=>`krafted_cloud_draft:${account.user.id}:${active.id}`;
save=function(){if(!account?.access.allowed||!active||!state.session)throw Error('Sign in with active access before saving.');const data=snapshot();localStorage.setItem(draftKey(),JSON.stringify({revision:active.revision,data}));pending=data;workspaceDirty=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>flushCloud().catch(()=>{}),500);cloudStatus()};
async function flushCloud(){clearTimeout(saveTimer);if(saving){await saving;return flushCloud()}if(!pending)return;if(!active||!account)throw Error('Sign in again to save.');const id=active.id,body=pending,revision=active.revision;pending=null;saving=(async()=>{try{const result=await api('/api/workspaces?id='+id,{method:'PUT',body:JSON.stringify({revision,data:body})});if(active?.id===id){active.revision=result.revision;saveFailure='';if(!pending)localStorage.removeItem(draftKey());else localStorage.setItem(draftKey(),JSON.stringify({revision:active.revision,data:pending}))}}catch(error){pending=pending||body;saveFailure=error.message;throw error}finally{saving=null;cloudStatus()}})();cloudStatus();await saving;if(pending)await flushCloud()}
async function refreshAccount(){try{account=await api('/api/account');if(!account.access.allowed){verificationView();return}const result=await api('/api/workspaces');workspaces=result.workspaces;const selected=sessionStorage.getItem('krafted_active:'+account.user.id);const target=workspaces.find(w=>w.id===selected)||workspaces.find(w=>w.kind==='founder');if(!target)throw Error('Your workspace could not be opened.');await loadCloudWorkspace(target.id)}catch(error){if(error.status===401){account=null;authView()}else{lock();panel('Could not open your account',error.message,'<button class="btn orange full" onclick="location.reload()">Try again</button><button class="btn secondary full" onclick="logout()">Sign out</button>')}}}
async function loadCloudWorkspace(id){active=await api('/api/workspaces?id='+id);pending=null;saveFailure='';sessionStorage.setItem('krafted_active:'+account.user.id,id);state=normalizeWorkspaceState({...active.data,user:{name:account.user.name||'',email:account.user.email},session:true});if(active.kind==='client'){state.brand.name=state.brand.name||active.name;state.brand.type=state.brand.type||'Client Brand';state.brand.created=true}unlock();render();const draft=localStorage.getItem(draftKey());if(draft){try{const saved=JSON.parse(draft);openDraftRecovery(saved)}catch{toast('A local draft could not be read. Cloud content is intact.')}}}
function openDraftRecovery(draft){document.getElementById('modalbox').innerHTML='<div class="kicker">Unsynced changes found</div><h2>Recover this browser’s draft?</h2><p>A previous save did not finish. You can review the local draft or keep the cloud version. If another device has newer edits, compare them before saving.</p><div class="actions"><button class="btn orange" id="recoverLocalDraft">Review local draft</button><button class="btn secondary" id="keepCloudDraft">Keep cloud version</button></div>';document.getElementById('modal').classList.add('show');document.getElementById('recoverLocalDraft').onclick=()=>{state=normalizeWorkspaceState({...draft.data,user:state.user,session:true});closeModal();render();toast('Local draft loaded for review. Use Save recovered draft when ready.');document.getElementById('view').insertAdjacentHTML('afterbegin','<button class="btn orange" onclick="save();render()">Save recovered draft</button>')};document.getElementById('keepCloudDraft').onclick=()=>{localStorage.removeItem(draftKey());closeModal()}}
render=function(){if(!account?.access.allowed||!state.session){return}originalRender();renderWorkspacePicker();accountControls()};
renderWorkspacePicker=function(){const options=workspaces.map(w=>`<option value="${w.id}" ${active?.id===w.id?'selected':''}>${w.kind==='founder'?'Founder Mode · My brand':esc(w.name)}</option>`).join('')+'<option value="__add">+ Add a client…</option>';const mode=document.querySelector('.mode');mode.classList.add('workspace-mode');mode.innerHTML=`<label for="workspaceSelect">${active.kind==='founder'?'FOUNDER MODE':'CLIENT WORKSPACE'}</label><select id="workspaceSelect" aria-label="Select brand workspace" onchange="chooseWorkspace(this.value)">${options}</select><div class="workspace-actions"><button onclick="openAddClient()">+ Add client</button>${active.kind==='client'?'<button onclick="openDeleteClient()">Delete client</button>':''}</div><small class="workspace-local">Private · saved to your account</small>`;let header=document.getElementById('workspaceHeaderButton');if(!header){header=document.createElement('button');header.id='workspaceHeaderButton';header.className='workspace-header-button';header.onclick=openWorkspaceManager;document.querySelector('.top .userbox').prepend(header)}header.textContent=(active.kind==='founder'?'Founder Mode':active.name)+' ▾'};
chooseWorkspace=async function(id){if(id==='__add'){renderWorkspacePicker();openAddClient();return}if(id===active.id)return;if(!canLeaveWorkspace()){renderWorkspacePicker();return}try{await flushCloud();sessionStorage.setItem('krafted_active:'+account.user.id,id);location.hash='overview';location.reload()}catch(error){toast(error.message);renderWorkspacePicker()}};
openWorkspaceManager=function(){document.getElementById('modalbox').innerHTML=`<div class="kicker">Your private workspaces</div><h2>Choose a brand</h2><div class="account-workspace-list">${workspaces.map(w=>`<button class="btn secondary" onclick="chooseWorkspace('${w.id}');closeModal()">${w.kind==='founder'?'Founder Mode':esc(w.name)}</button>`).join('')}</div><div class="actions"><button class="btn orange" onclick="openAddClient()">+ Add client</button>${active.kind==='client'?'<button class="btn secondary" onclick="openDeleteClient()">Delete this client</button>':''}<button class="btn secondary" onclick="closeModal()">Done</button></div>`;document.getElementById('modal').classList.add('show')};
addClientWorkspace=async function(){if(!canLeaveWorkspace())return;const button=document.querySelector('#addClientForm button[type="submit"]');button.disabled=true;try{await flushCloud();const name=document.getElementById('clientWorkspaceName').value.trim();const fresh=structuredClone(DEFAULT);fresh.brand={...fresh.brand,name,type:'Client Brand',created:true};const created=await api('/api/workspaces',{method:'POST',body:JSON.stringify({name,data:fresh})});sessionStorage.setItem('krafted_active:'+account.user.id,created.id);location.hash='overview';location.reload()}catch(error){document.getElementById('clientWorkspaceError').textContent=error.message;button.disabled=false}};
workspaceLabel=function(){return active.kind==='founder'?'Founder Mode':active.name};
openDeleteClient=function(){if(active.kind!=='client')return;document.getElementById('modalbox').innerHTML=`<div class="kicker">Delete client workspace</div><h2>Delete ${esc(active.name)}?</h2><p>This permanently removes this client’s cloud-saved brand data and chats. Other workspaces are kept.</p><label for="deleteClientName">Type ${esc(active.name)} to confirm</label><input class="select" id="deleteClientName"><p id="deleteClientError" role="alert"></p><div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn orange" onclick="deleteClientWorkspace()">Delete client</button></div>`;document.getElementById('modal').classList.add('show')};
deleteClientWorkspace=async function(){if(active.kind!=='client'||document.getElementById('deleteClientName').value!==active.name){document.getElementById('deleteClientError').textContent='Enter the exact client name.';return}try{await flushCloud();await api('/api/workspaces?id='+active.id,{method:'DELETE'});localStorage.removeItem(draftKey());location.hash='overview';location.reload()}catch(error){document.getElementById('deleteClientError').textContent=error.message}};
logout=async function(){loggingOut=true;try{await flushCloud()}catch{if(!confirm('Cloud saving failed. Sign out and keep the unsynced draft in this browser?')){loggingOut=false;return}}try{await identityLogout()}finally{account=null;active=null;pending=null;state=structuredClone(DEFAULT);lock();location.reload()}};
window.openAccountPanel=function(){document.getElementById('modalbox').innerHTML=`<div class="kicker">Your account</div><h2>${esc(account.user.name||'Account settings')}</h2><p>${esc(account.user.email)}</p><p>Access: ${account.access.reason==='owner'?'Owner':'Verified member'}</p><p>All workspaces belong to this account. Cloud saves follow you across devices.</p><div class="actions"><button class="btn secondary" onclick="openLocalImport()">Import old browser workspaces</button><button class="btn secondary" onclick="logout()">Sign out</button><button class="btn orange" onclick="closeModal()">Done</button></div>`;document.getElementById('modal').classList.add('show')};
window.openLocalImport=function(){const legacy=new BrandWorkspaceStorage(localStorage,KEY,LEGACY_KEY);const registry=legacy.registry();const entries=[{id:'founder',name:'Personal browser workspace'},...registry.clients];document.getElementById('modalbox').innerHTML=`<div class="kicker">Import browser data</div><h2>Bring your existing work into this account</h2><p>Only import workspaces you own. Each import creates a separate client workspace so current cloud data is kept. Browser originals stay untouched.</p><div class="account-workspace-list">${entries.filter(e=>localStorage.getItem(legacy.key(e.id))||(e.id==='founder'&&localStorage.getItem(LEGACY_KEY))).map(e=>`<button class="btn secondary" data-import-id="${e.id}">${esc(e.name)}</button>`).join('')||'<p>No old browser workspaces found on this device.</p>'}</div><p id="importMessage" role="status"></p><button class="btn secondary" onclick="closeModal()">Done</button>`;document.getElementById('modal').classList.add('show');document.querySelectorAll('[data-import-id]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await flushCloud();legacy.activeId=button.dataset.importId;const data=legacy.read();if(!data)throw Error('No saved data was found.');const created=await api('/api/workspaces',{method:'POST',body:JSON.stringify({name:(data.brand?.name||'Imported brand').slice(0,80),data})});workspaces.push(created);renderWorkspacePicker();button.textContent='Imported';document.getElementById('importMessage').textContent='Imported successfully. Select the imported workspace from the dropdown.'}catch(error){document.getElementById('importMessage').textContent=error.message;button.disabled=false}})};
resetActiveWorkspace=function(){toast('Use workspace deletion to remove a client. Your personal cloud workspace is protected.')};
window.addEventListener('beforeunload',event=>{if(pending||saving){event.preventDefault();event.returnValue=''}});
document.addEventListener('input',e=>{if(e.target.closest('#view'))workspaceDirty=true},true);document.addEventListener('change',e=>{if(e.target.closest('#view'))workspaceDirty=true},true);
onAuthChange((event,user)=>{if(booting||loggingOut)return;if(event==='logout'||(user&&account&&user.id!==account.user.id)){account=null;active=null;pending=null;clearTimeout(saveTimer);lock();location.reload()}});
(async()=>{lock();panel('Opening your Brand OS','Checking your secure session…');try{settings=await getSettings();const callback=await handleAuthCallback();if(callback?.type==='recovery'||callback?.type==='invite'){authView('reset')}else await refreshAccount()}catch(error){panel('Sign-in setup needs attention','Secure authentication is temporarily unavailable. Please try again.','<button class="btn orange full" onclick="location.reload()">Retry</button>');message(error.message)}finally{booting=false}})();
