import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function harness(){
 const node=()=>({dataset:{},style:{},setAttribute(){},append(){},replaceChildren(){},querySelectorAll(){return[]},classList:{add(){},remove(){}},insertAdjacentHTML(){}});
 const nodes=new Map();const state={session:false,brand:{name:'Test'},clarity:{answers:{offer:'Design audit'}},archetype:{},dna:{data:{purpose:'Original purpose'},version:1,approved:true},guidelines:{data:{foundation:[['Purpose','Original',true]]},version:1,approved:true,history:[]},multiplier:{source:'Original',platforms:['Email'],frequency:'3 posts/week',duration:'14 Days'},websiteBrief:{type:'Landing page',builder:'Any builder',cta:'Book',prompt:'Original'}};
 const ctx={state,console,setTimeout,clearTimeout,AbortController,window:{confirm:()=>true},document:{getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},createElement:node,body:node(),querySelectorAll:()=>[]},ARCHETYPES:{},websiteSource:()=>({brand:state.brand,clarity:state.clarity.answers,dna:state.dna,guidelines:{data:state.guidelines.data},archetype:{},assets:{},funnel:{}}),guidelineStore:()=>state.guidelines,websiteStore:()=>state.websiteBrief,dnaPage(){},websitePage(){},guidelinesPage(){},multiplierPage(){},render(){},commitGuidelineProposal(){},resetMultiplier(){},save(){},toast(){},esc:String};vm.createContext(ctx);vm.runInContext(readFileSync('assets/brand-os-ai.js','utf8'),ctx);return ctx;
}
test('failed generation leaves existing content untouched and displays an error',async()=>{const ctx=harness(),before=JSON.stringify(ctx.state);ctx.fetch=async()=>Response.json({error:'Try again'},{status:502});let applied=false;await ctx.runBrandOsAI('dna',{},()=>{applied=true});assert.equal(applied,false);assert.equal(JSON.stringify(ctx.state),before);assert.equal(vm.runInContext('brandOsJobMessage',ctx),'Try again')});
test('source changes during an AI request prevent stale output from overwriting edits',async()=>{const ctx=harness();ctx.fetch=async()=>{ctx.state.brand.name='Edited while generating';return Response.json({data:{prompt:'Generated'}})};let applied=false;await ctx.runBrandOsAI('website',{},()=>{applied=true});assert.equal(applied,false);assert.match(vm.runInContext('brandOsJobMessage',ctx),/inputs changed/)});
test('saving AI branch rolls back on storage failure',()=>{const ctx=harness(),previous=ctx.state.dna;ctx.save=()=>{throw Error('QuotaExceeded')};assert.throws(()=>ctx.aiSaveBranch('dna',{data:{purpose:'New'}}),/storage is full/);assert.equal(ctx.state.dna,previous)});
test('guideline generations preserve protected sections, create a draft and retain previous approved version',()=>{const ctx=harness();ctx.state.guidelines.sectionMeta={foundation:{manuallyEdited:true}};ctx.guidelineSource=()=> 'source';ctx.guidelineSourceSnapshot=()=>({versions:{dna:1}});ctx.guidelineSectionName=k=>k;ctx.saveAiGuidelines({data:{foundation:[{label:'Purpose',value:'Changed',sourced:false}],verbal:[{label:'Voice',value:'Warm',sourced:true}]},generatedAt:'2026-10-07',model:'test'});assert.equal(ctx.state.guidelines.data.foundation[0][1],'Original');assert.equal(ctx.state.guidelines.data.verbal[0][1],'Warm');assert.equal(ctx.state.guidelines.approved,false);assert.equal(ctx.state.guidelines.previous.approved,true)});
