import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
import {handleBrandie,friendlyError} from '../server/brandie.mjs';
import {instructions} from '../server/kraftie-instructions.mjs';
test('Kraftie backend uses its own instructions and funnel context',async()=>{let sent;const request=new Request('https://example.com/api/kraftie',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:'What is my CTA?'}],context:{funnel:{cta:'Book a call'}}})});const response=await handleBrandie(request,{assistantName:'Kraftie',assistantInstructions:instructions,model:'gpt-5-mini',createClient:()=>({responses:{create:async args=>{sent=args;return(async function*(){yield{type:'response.output_text.delta',delta:'Book a call'};yield{type:'response.completed'}})()}}})});assert.match(await response.text(),/Book a call/);assert(sent.instructions.startsWith(instructions));assert.match(sent.instructions,/Funnel strategist/);assert.match(sent.input[0].content,/Book a call/);assert.match(friendlyError({status:401},'Kraftie'),/^Kraftie/)});
test('Kraftie history is separate and sends only selected context without image bytes',async()=>{let sent;const original={conversations:[{id:'brandie-existing',messages:[]}],activeId:'brandie-existing'};const state={session:false,brand:{name:'Sample',type:'Agency'},dna:{approved:true,data:{audience:'Founders'}},archetype:{primary:'creator'},brandie:original};const ctx={state,crypto:webcrypto,AbortController,TextDecoder,setTimeout,clearTimeout,location:{hash:'#kraftie'},save:()=>{},render:()=>{},toast:()=>{},esc:String,document:{getElementById:()=>({value:'Help me improve my CTA',focus(){}})},assetStore:()=>({items:[{name:'logo.png',group:'Logos',preview:'data:image/png;base64,abc'}],colors:[]}),guidelineStore:()=>({data:{voice:'clear'},approved:true}),funnelStore:()=>({status:'complete',answers:{cta:'Book a call'}}),fetch:async(url,options)=>{sent={url,body:JSON.parse(options.body)};return new Response('{"type":"delta","text":"Try a clear next step."}\n{"type":"done"}\n',{headers:{'content-type':'application/x-ndjson'}})}};vm.createContext(ctx);vm.runInContext(readFileSync('assets/chat-attachments.js','utf8'),ctx);vm.runInContext(readFileSync('assets/kraftie-live.js','utf8'),ctx);ctx.kraftieStore().sources.guidelines=false;await ctx.kraftieSend();assert.equal(sent.url,'/api/kraftie');assert.equal(sent.body.context.guidelines,null);assert.equal(sent.body.context.funnel.cta,'Book a call');assert(!JSON.stringify(sent.body).includes('base64'));assert.equal(state.brandie,original);assert.equal(state.kraftie.conversations[0].messages[1].text,'Try a clear next step.');assert.equal(state.kraftie.conversations[0].messages[1].pending,false)});
