import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const code=readFileSync('assets/workspace-store.js','utf8');
function harness(){const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const ctx={};vm.createContext(ctx);vm.runInContext(code+'\nthis.Store=BrandWorkspaceStorage;',ctx);return {Store:ctx.Store,storage,data}}
test('existing founder state stays at its original key while clients start and save independently',()=>{const {Store,storage,data}=harness();storage.setItem('founder',JSON.stringify({brand:{name:'Personal'},brandie:{conversations:['private']}}));const first=new Store(storage,'founder','legacy');const original=storage.getItem('founder');first.add('Client A',{brand:{name:'Client A'},dna:{data:{}}},'client_a');const client=new Store(storage,'founder','legacy');assert.equal(client.activeId,'client_a');assert.equal(client.read().brand.name,'Client A');assert.equal(client.read().brandie,undefined);client.save({brand:{name:'Changed client'},brandie:{conversations:['client only']}});assert.equal(storage.getItem('founder'),original);client.select('founder');const founder=new Store(storage,'founder','legacy');assert.equal(founder.read().brandie.conversations[0],'private');assert.equal(data.size,3)});
test('deleting client removes only its data and prevents old tabs from resurrecting it',()=>{const {Store,storage}=harness();storage.setItem('founder','{"brand":{"name":"Personal"}}');const founder=new Store(storage,'founder','legacy');founder.add('A',{a:1},'client_a');const oldTab=new Store(storage,'founder','legacy');oldTab.add('B',{b:2},'client_b');const active=new Store(storage,'founder','legacy');active.delete('client_a');assert.equal(storage.getItem('founder_client_a'),null);assert(storage.getItem('founder_client_b'));assert.throws(()=>oldTab.save({a:2}),/deleted/);assert.throws(()=>active.delete('founder'),/cannot be deleted/);assert.equal(storage.getItem('founder'),' {"brand":{"name":"Personal"}}'.trim())});
test('failed client registry write rolls back the new client and keeps founder unchanged',()=>{const {Store,storage}=harness();storage.setItem('founder','{}');const store=new Store(storage,'founder','legacy'),set=storage.setItem;storage.setItem=(k,v)=>{if(k.endsWith('_workspaces'))throw Error('quota');set(k,v)};assert.throws(()=>store.add('A',{a:1},'client_a'),/quota/);assert.equal(storage.getItem('founder_client_a'),null);assert.equal(storage.getItem('founder'),'{}')});
test('legacy founder data loads; invalid names, duplicate clients and corrupted registry are rejected',()=>{const {Store,storage}=harness();storage.setItem('legacy','{"brand":{"name":"Legacy"}}');const store=new Store(storage,'founder','legacy');assert.equal(store.read().brand.name,'Legacy');assert.throws(()=>store.add(' ',{},'client_a'));store.add('A',{},'client_a');assert.throws(()=>store.add('a',{},'client_b'),/already exists/);storage.setItem('founder_workspaces','bad');assert.throws(()=>new Store(storage,'founder','legacy'));assert.equal(storage.getItem('legacy'),' {"brand":{"name":"Legacy"}}'.trim())});
test('all application scripts including workspace integration parse together',()=>{const html=readFileSync('index.html','utf8');const code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);for(const m of html.matchAll(/<script src="([^"]+)"/g))code.push(readFileSync(m[1],'utf8'));new vm.Script(code.join('\n'))});
